// <auto-generated />
using System;
using Eventide.BracketService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Eventide.BracketService.Infrastructure.Migrations
{
    [DbContext(typeof(BracketDbContext))]
    [Migration("20260423221206_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Eventide.BracketService.Domain.Entities.Bracket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalRounds")
                        .HasColumnType("integer");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId")
                        .IsUnique();

                    b.ToTable("Brackets");
                });

            modelBuilder.Entity("Eventide.BracketService.Domain.Entities.Bracket", b =>
                {
                    b.OwnsMany("Eventide.BracketService.Domain.Entities.BracketRound", "Rounds", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("BracketId")
                                .HasColumnType("uuid");

                            b1.Property<int>("RoundNumber")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("BracketId");

                            b1.ToTable("BracketRound");

                            b1.WithOwner()
                                .HasForeignKey("BracketId");

                            b1.OwnsMany("Eventide.BracketService.Domain.Entities.BracketMatch", "Matches", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("BracketRoundId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("Player1Id")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("Player2Id")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("RoundNumber")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Status")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<Guid?>("WinnerId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("BracketRoundId");

                                    b2.ToTable("BracketMatch");

                                    b2.WithOwner()
                                        .HasForeignKey("BracketRoundId");
                                });

                            b1.Navigation("Matches");
                        });

                    b.Navigation("Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
